### ISSUE TITLE
One part, two libraries

### ISSUE THREAD

**Issue by sethladd** [sigmundch/DEP-resolved-part-of#1]
In the wild, we've see a single part file get included into two different libraries. This is the common solution to dealing with platform specific code.

For example:

```
library awesome_io;

import 'dart:io';
part 'common.dart';
```

and

```
library awesome_html;

import 'dart:html';
part 'common.dart';
```

and

```
part of awesome;

common_stuff
```

How would this proposal work in that case?

(and there was a reason why common.dart wasn't a library... I think it was because it needed to use private names from the main library file.

**Comment by sigmundch** [comment]
my currently inclination is that no, it wouldn't be supported anymore. I'm hoping we can address config-specific libraries directly instead. I understand there is work in progress for that, but I don't know the latest.

**Comment by sigmundch** [comment]
closing "as designed"
